package unittests.renderer;

import static org.junit.jupiter.api.Assertions.*;

import java.util.LinkedList;
import java.util.List;

import org.junit.jupiter.api.Test;
import geometries.*;
import primitives.*;
import renderer.*;
import renderer.Camera.rayCreationSpace;

/**
 * This class contains integration tests for intersections between rays
 * generated by a camera and various geometrical objects (spheres, planes,
 * triangles). It verifies that the number of intersections matches the expected
 * result for each geometry.
 * 
 * <p>
 * Tests include checking intersections for spheres, planes, and triangles using
 * a camera's rays through a 3x3 view plane. The number of expected
 * intersections is compared with the actual result.
 * </p>
 */
class CameraIntersectionsIntegrationTests {
	private static final int NX = 3; // Number of horizontal pixels in the view plane.
	private static final int NY = 3; // Number of vertical pixels in the view plane.

	/**
	 * Returns the number of intersection points between rays cast from a camera and
	 * a geometry object.
	 *
	 * @param camera   the Camera object used to cast the rays
	 * @param geometry the Geometry object to intersect with the rays
	 * @return the number of intersection points found
	 */
	int intersects(Camera camera, Geometry geometry) {
		List<Point> intersects = new LinkedList<>(); // Initialize an empty list to store intersection points.
		// Iterate over all the pixels in the camera's view plane.
		for (int i = 0; i < NX; i++) {
			for (int j = 0; j < NY; j++) {
				// Construct a ray from the camera through the current pixel.
				rayCreationSpace details = camera.constructRay(NX, NY, i, j);
				Ray ray = new Ray(details.p0(), details.pIJ().subtract(details.p0()));
				// Find all intersection points between the ray and the geometry.
				List<Point> points = geometry.findIntersections(ray);
				if (points != null) {
					intersects.addAll(points);
				}
			}
		}
		// Return the total number of intersection points found.
		return intersects.size();
	}

	/**
	 * Test method for intersections with spheres.
	 *
	 * @throws CloneNotSupportedException if cloning is not supported
	 */
	@Test
	void testSphere() throws CloneNotSupportedException {
		// TC01: Testing a sphere directly in front of the camera
		Sphere sphere = new Sphere(new Point(0, 0, -3), 1);
		Camera camera = Camera.getBuilder().setLocation(new Point(0, 0, 0))
				.setDirection(new Vector(0, 0, -1), new Vector(0, -1, 0)).setViewPlaneSize(NX, NY)
				.setViewPlaneDistance(1).build();
		assertEquals(2, intersects(camera, sphere), "Wrong number of intersections (sphere test 01)");

		// TC02: Testing a larger sphere that intersects multiple intersects
		sphere = new Sphere(new Point(0, 0, -2.5), 2.5);
		camera = Camera.getBuilder().setLocation(new Point(0, 0, 0.5))
				.setDirection(new Vector(0, 0, -1), new Vector(0, -1, 0)).setViewPlaneSize(NX, NY)
				.setViewPlaneDistance(1).build();
		assertEquals(18, intersects(camera, sphere), "Wrong number of intersections (sphere test 02)");

		// TC03: Testing a sphere with adjusted camera position
		sphere = new Sphere(new Point(0, 0, -2), 2);
		camera = Camera.getBuilder().setLocation(new Point(0, 0, 0.5))
				.setDirection(new Vector(0, 0, -1), new Vector(0, -1, 0)).setViewPlaneSize(NX, NY)
				.setViewPlaneDistance(1).build();
		assertEquals(10, intersects(camera, sphere), "Wrong number of intersections (sphere test 03)");

		// TC04: Testing a sphere that intersects many intersects
		sphere = new Sphere(new Point(0, 0, -2), 4);
		camera = Camera.getBuilder().setLocation(new Point(0, 0, 0.5))
				.setDirection(new Vector(0, 0, -1), new Vector(0, -1, 0)).setViewPlaneSize(NX, NY)
				.setViewPlaneDistance(1).build();
		assertEquals(9, intersects(camera, sphere), "Wrong number of intersections (sphere test 04)");

		// TC05: Testing a sphere that does not intersect with intersects
		sphere = new Sphere(new Point(0, 0, 1), 0.5);
		camera = Camera.getBuilder().setLocation(new Point(0, 0, 0.5))
				.setDirection(new Vector(0, 0, -1), new Vector(0, -1, 0)).setViewPlaneSize(NX, NY)
				.setViewPlaneDistance(1).build();
		assertEquals(0, intersects(camera, sphere), "Wrong number of intersections (sphere test 05)");
	}

	/**
	 * Test method for intersections with planes.
	 *
	 * @throws CloneNotSupportedException if cloning is not supported
	 */
	@Test
	void testPlane() throws CloneNotSupportedException {
		// TC01: Testing a plane parallel to the view plane
		Plane plane = new Plane(new Point(0, 0, -1), new Vector(0, 0, 2));
		Camera camera = Camera.getBuilder().setLocation(new Point(0, 0, 0))
				.setDirection(new Vector(0, 0, -1), new Vector(0, -1, 0)).setViewPlaneSize(NX, NY)
				.setViewPlaneDistance(1).build();
		assertEquals(9, intersects(camera, plane),
				"Failed to find all intersection points with the plane (plane test 01)");

		// TC02: Testing a plane at an angle to the view plane
		plane = new Plane(new Point(0, 0, -1), new Vector(0, 2, 4));
		assertEquals(9, intersects(camera, plane),
				"Failed to find all intersection points with the plane (plane test 02)");

		// TC03: Testing a plane at a different angle to the view plane
		plane = new Plane(new Point(0, 0, -1), new Vector(0, 2, 2));
		assertEquals(6, intersects(camera, plane),
				"Failed to find all intersection points with the plane (plane test 03)");
	}

	/**
	 * Test method for intersections with triangles.
	 *
	 * @throws CloneNotSupportedException if cloning is not supported
	 */
	@Test
	void testTriangle() throws CloneNotSupportedException {
		// TC01: Testing a triangle that does not intersect with any intersects
		Triangle triangle = new Triangle(new Point(0, 1, -2), new Point(1, -1, -2), new Point(-1, -1, -2));
		Camera camera = Camera.getBuilder().setLocation(new Point(0, 0, 0))
				.setDirection(new Vector(0, 0, -1), new Vector(0, -1, 0)).setViewPlaneSize(NX, NY)
				.setViewPlaneDistance(1).build();
		assertEquals(1, intersects(camera, triangle),
				"Failed to find all intersection points with the triangle (triangle test 01)");

		// TC02: Testing a triangle that intersects with multiple intersects
		triangle = new Triangle(new Point(0, 20, -2), new Point(1, -1, -2), new Point(-1, -1, -2));
		assertEquals(2, intersects(camera, triangle),
				"Failed to find all intersection points with the triangle (triangle test 02)");
	}

}
