package unittests.renderer;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;
import geometries.*;
import primitives.*;
import renderer.*;
/**
 * This class contains integration tests for intersections between rays generated by a camera 
 * and various geometrical objects (spheres, planes, triangles).
 * It verifies that the number of intersections matches the expected result for each geometry.
 * 
 * <p>Tests include checking intersections for spheres, planes, and triangles using a camera's rays 
 * through a 3x3 view plane. The number of expected intersections is compared with the actual result.</p>
 * 
 * @author Yehuda
 */
class CameraIntersectionsIntegrationTests {

	/**
	 * Helper method to test intersections between a geometry and a camera's rays.
	 * This method iterates over all pixels in the View Plane and counts the number 
	 * of intersection points between the rays constructed from the camera and the geometry.
	 *
	 * @param geometry The geometry (e.g., Sphere, Plane, Triangle) to check for intersections with.
	 * @param expectedIntersections The expected number of intersection points between the geometry and the camera's rays.
	 * @param camera The camera object used to create the rays through the View Plane.
	 */
    private void testIntersectionWithGeometry(Intersectable geometry, int expectedIntersections, Camera camera) {
        int actualIntersections = 0;
        
        // Loop through all the pixels in the 3x3 view plane
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                Ray ray = camera.constructRayThroughPixel(3, 3, j, i);  // Construct a ray for each pixel
                if (geometry.findIntersections(ray) != null) {
                    actualIntersections++;
                }
            }
        }
        
        // Assert that the number of intersections matches the expected value
        assertEquals(expectedIntersections, actualIntersections, "Number of intersections does not match the expected value.");
    }
    
    /**
     * Tests intersections with a series of spheres. Each sphere is tested for the expected number of intersection points
     * with rays constructed by the camera.
     * 
     * @param camera The camera to generate rays from.
     */
    @Test
    void testIntersectionWithSphere() {
    	 // First test case for Sphere (r = 1, center = (0, 0, -3))
        Sphere sphere1 = new Sphere(new Point(0, 0, -3), 1);
        Camera camera1 = new Camera(new Point(0, 0, 0), new Vector(0, 0, 1), new Vector(0, 1, 0));
        testIntersectionWithGeometry(sphere1, 2, camera1);  // Expecting 2 intersections

        // Second test case for Sphere (r = 2.5, center = (0, 0, -2.5))
        Sphere sphere2 = new Sphere(new Point(0, 0, -2.5), 2.5);
        Camera camera2 = new Camera(new Point(0, 0, 0.5), new Vector(0, 0, 1), new Vector(0, 1, 0));
        testIntersectionWithGeometry(sphere2, 18, camera2);  // Expecting 18 intersections

        // Third test case for Sphere (r = 2, center = (0, 0, -2))
        Sphere sphere3 = new Sphere(new Point(0, 0, -2), 2);
        Camera camera3 = new Camera(new Point(0, 0, 0.5), new Vector(0, 0, 1), new Vector(0, 1, 0));
        testIntersectionWithGeometry(sphere3, 10, camera3);  // Expecting 10 intersections
        
        // Fourth test case for Sphere (r = 4, center = (0, 0, -1))
        Sphere sphere4 = new Sphere(new Point(0, 0, -1), 4);
        Camera camera4 = new Camera(new Point(0, 0, 0), new Vector(0, 0, 1), new Vector(0, 1, 0));
        testIntersectionWithGeometry(sphere4, 9, camera4);  // Expecting 9 intersections
        
        // Fifth test case for Sphere (r = 0.5, center = (0, 0, 1))
        Sphere sphere5 = new Sphere(new Point(0, 0, 1), 0.5);
        Camera camera5 = new Camera(new Point(0, 0, 0), new Vector(0, 0, 1), new Vector(0, 1, 0));
        testIntersectionWithGeometry(sphere5, 0, camera5);  // Expecting 0 intersections
    }
    
    /**
     * Tests intersections with a series of planes. Each plane is tested for the expected number of intersection points
     * with rays constructed by the camera.
     * 
     * @param camera The camera to generate rays from.
     */
    @Test
    void testIntersectionWithPlane() {
    	// מצלמה במיקום (0, 0, 0)
        Camera camera = new Camera(new Point(0, 0, 0), new Vector(0, 0, 1), new Vector(0, 1, 0));

        // First test case for Plane (Normal = (0, 1, 0), Point = (0, 0, 1))
        Plane plane1 = new Plane(new Point(0, 0, 1), new Vector(0, 1, 0));
        testIntersectionWithGeometry(plane1, 9, camera);  // Expecting 9 intersections

        // Second test case for Plane (Normal = (0, -1, 0), Point = (0, 0, 2))
        Plane plane2 = new Plane(new Point(0, 0, 2), new Vector(0, -1, 0));
        testIntersectionWithGeometry(plane2, 9, camera);  // Expecting 9 intersections

        // Third test case for Plane (Normal = (1, 0, 0), Point = (0, 0, 3))
        Plane plane3 = new Plane(new Point(0, 0, 3), new Vector(1, 0, 0));
        testIntersectionWithGeometry(plane3, 6, camera);  // Expecting 6 intersections
    }
    
    /**
     * Tests intersections with a series of triangles. Each triangle is tested for the expected number of intersection points
     * with rays constructed by the camera.
     * 
     * @param camera The camera to generate rays from.
     */
    @Test
    void testIntersectionWithTriangles() {
        // מצלמה במיקום (0, 0, 0)
        Camera camera = new Camera(new Point(0, 0, 0), new Vector(0, 0, 1), new Vector(0, 1, 0));

        // First test case for Triangle with one intersection point
        Point p1_1 = new Point(0, 1, -2);
        Point p2_1 = new Point(1, -1, -2);
        Point p3_1 = new Point(-1, -1, -2);
        Triangle triangle1 = new Triangle(new Point[]{p1_1, p2_1, p3_1});  // להעביר מערך

        // Perform the intersection test for triangle1, expecting 1 intersection
        testIntersectionWithGeometry(triangle1, 1, camera);

        // Second test case for Triangle with two intersection points
        Point p1_2 = new Point(0, 20, -2);
        Point p2_2 = new Point(1, -1, -2);
        Point p3_2 = new Point(-1, -1, -2);
        Triangle triangle2 = new Triangle(new Point[]{p1_2, p2_2, p3_2});  // להעביר מערך

        // Perform the intersection test for triangle2, expecting 2 intersections
        testIntersectionWithGeometry(triangle2, 2, camera);
    }



}
